name = "dhafin-personal-site"
compatibility_date = "2026-05-02"

[vars]
PUBLIC_SITE_URL = "https://dhaf.in"
SANITY_STUDIO_PROJECT_ID = "a7az8pap"
SANITY_STUDIO_DATASET = "production"
SANITY_API_VERSION = "2025-02-19"

[assets]
directory = "dist"
not_found_handling = "single-page-application"
run_worker_first = true

[[routes]]
pattern = "dhaf.in"
custom_domain = true
zone_name = "dhaf.in"

[[routes]]
pattern = "www.dhaf.in"
custom_domain = true
zone_name = "dhaf.in"

[[routes]]
pattern = "portfolio.dhaf.in"
custom_domain = true
zone_name = "dhaf.in"

[[routes]]
pattern = "video.dhaf.in"
custom_domain = true
zone_name = "dhaf.in"

[[routes]]
pattern = "midjourney.dhaf.in"
custom_domain = true
zone_name = "dhaf.in"
